version: '3'

networks:
  easy-docker-host:
    external: true

services:
  lina534:
    image: hub.atempo.cloud/releases/lina:5.3.4.24031-full
    pull_policy: always    
    container_name: lina534
    restart: unless-stopped
    env_file:
     - stack.env    
    ports:
      - 8181
    labels:
      - traefik.http.services.lina534.loadbalancer.server.port=8181           
    networks:
      - easy-docker-host
  lina534-agent01:
    image: hub.atempo.cloud/releases/lina-agent:5.3.4.24031
    pull_policy: always    
    container_name: lina534-agent01
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina534
      - LINA_AGENTNAME=lina534-agent01
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina534"
  lina534-agent02:
    image: hub.atempo.cloud/releases/lina-agent:5.3.4.24031
    pull_policy: always    
    container_name: lina534-agent02
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina534
      - LINA_AGENTNAME=lina534-agent02
    env_file:
     - stack.env       
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina534"
  lina534-agent03:
    image: hub.atempo.cloud/releases/lina-agent:5.3.4.24031
    pull_policy: always    
    container_name: lina534-agent03
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina534
      - LINA_AGENTNAME=lina534-agent03
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina534"
  lina534-agent04:
    image: hub.atempo.cloud/releases/lina-agent:5.3.4.24031
    pull_policy: always    
    container_name: lina534-agent04
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina534
      - LINA_AGENTNAME=lina534-agent04   
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina534"      