version: '3'

networks:
  easy-docker-host:
    external: true

volumes:
  miria41beta_postgres_data:

services:
  miria41beta-db:
    image: postgres:13.5
    pull_policy: always
    container_name: miria41beta-db
    restart: unless-stopped
    volumes:
      - miria41beta_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_HOST_AUTH_METHOD=trust # /!\ Unsecured but should fix DB backup from miria  
    networks:
      - easy-docker-host
    env_file:
     - stack.env      
  miria41beta:
    image: hub.atempo.cloud/internal/miria:4.1-latest
    pull_policy: always
    container_name: miria41beta
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 80
      - 443
      - 9111
      - 2524
      - 5432
    hostname: miria41beta
    depends_on:
      - "miria41beta-db"
    environment:
      - POSTGRES_SERVER=miria41beta-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_PORT=5432
      - MM_AGENT=1
      - MM_SERVER=1
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - POSTGRES_SERVER=miria41beta-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=rzKX2C5%bVY
#      - POSTGRES_PORT=5432
#      - DB_NAME=MIRIA
#      - INITIAL_PASSWORD=ATempo1992$$
#      - DEMO_LICENSE=1

  miria41beta-agent1:
    image:  hub.atempo.cloud/internal/miria-agent:4.1-latest
    pull_policy: always
    container_name: miria41beta-agent1
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: miria41beta-agent1
    environment:
      - MIRIA_SERVER=miria41beta
    depends_on:
      - "miria41beta"
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - CUSTOM_CMD=mkdir -p /mnt/nfs-nas && mount -v -o vers=4,loud nfs-nas:/ /nas-mounts/nfs1 

  miria41beta-agent2:
    image:  hub.atempo.cloud/internal/miria-agent:4.1-latest
    pull_policy: always
    container_name: miria41beta-agent2
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: miria41beta-agent2
    environment:
      - MIRIA_SERVER=miria41beta
    depends_on:
      - "miria41beta"
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - CUSTOM_CMD=mkdir -p /mnt/nfs-nas && mount -v -o vers=4,loud nfs-nas:/ /nas-mounts/nfs1