version: '3'
# Shared services provide S3 storage / SMTP + WebMail / Syslog + WebUI service
networks:
  easy-docker-host:
    external: true

services:
  mail:
    image: maildev/maildev
    pull_policy: always    
    container_name: mail
    restart: unless-stopped
    ports:
      - 80
      - 25:25
    labels:
      - traefik.http.services.common-mail.loadbalancer.server.port=80
    environment:
      - TZ=Europe/Paris
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    networks:
      - easy-docker-host
    healthcheck:
      disable: true
    env_file:
     - stack.env
  syslog:
    image: pbertera/syslogserver
    pull_policy: always    
    container_name: syslog
    restart: unless-stopped
    ports:
      - 80 # Admin console
      - 514:514/udp  
    networks:
      - easy-docker-host
    env_file:
     - stack.env
  minio-s3:
    image: quay.io/minio/minio
    pull_policy: always    
    container_name: minio-s3
    restart: unless-stopped
    command: server /data --console-address ":9001" --address ":443"
    ports:
      - 443 # To use same data (S3) port from container and externally
      - 9001 # Administration console
    volumes:
     - /data
    labels:
      - traefik.http.services.common-minio-s3.loadbalancer.server.port=443
      # Will match all URL containing minio-s3.* => forwarding to s3 data port
      - traefik.http.routers.common-minio-s3.rule=HostRegexp(`{miniosubdomains:^minio-s3.*}`)
      - traefik.http.routers.common-minio-s3.service=common-minio-s3
      - traefik.http.services.common-minio-console.loadbalancer.server.port=9001
      # Will match all URL containing minio-console.* => forwarding to admin console port
      - traefik.http.routers.common-minio-console.rule=HostRegexp(`{minioconsolesubdomains:^minio-console.*}`)
      - traefik.http.routers.common-minio-console.service=common-minio-console    
    networks:
      - easy-docker-host
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed :
#    environment:
#      - MINIO_ROOT_USER=root
#      - MINIO_ROOT_PASSWORD=ATempo1992$$
  nfs-nas:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs-nas
    restart: unless-stopped
    privileged: true
    networks:
      - easy-docker-host    
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ${NFS_ROOT_ON_HOST}:/data
    ports:
      - 2049 