version: '3'

networks:
  easy-docker-host:
    external: true

services:
  doku:
    image: amerkurev/doku
    pull_policy: always    
    container_name: doku
    restart: unless-stopped
    ports:
      - 9090 
    networks:
      - easy-docker-host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro