services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_NO_ANALYTICS=1      
    networks:
      - easy-docker-host
     
networks:
  easy-docker-host:
    external: true              