version: "3"

networks:
  easy-docker-host:
    external: true

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: always
    ports:
      - 9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9093
      - JVM_OPTS=-Xms32M -Xmx64M
      - SERVER_SERVLET_CONTEXTPATH=/
    networks:
      - easy-docker-host
    depends_on:
      - kafka
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - easy-docker-host
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
      - 9093
    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://${EXTERNAL_HOST}:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - easy-docker-host

  redpanda:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda
    ports:
      - 8080
    networks:
      - easy-docker-host
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9093