version: '3'

networks:
  easy-docker-host:
    external: true

services:
  lina61rc-master:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always    
    container_name: lina61rc-master
    hostname: lina61rc-master
    restart: unless-stopped
    ports:
      - 443 # Used for both webUI only
      - 8181 # Used for data (to nodes and from agents) 
    environment:
      - LINA_MASTERMODE=1
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61rc-master.loadbalancer.server.port=443
      - traefik.http.routers.lina61rc-master.rule=HostRegexp(`{lina61rcsubdomains:^lina61rc-master.*}`)
      - traefik.http.routers.lina61rc-master.service=lina61rc-master
      - traefik.http.services.lina61rc-master-data.loadbalancer.server.port=8181
      - traefik.http.routers.lina61rc-master-data.rule=HostRegexp(`{lina61rcdatasubdomains:^lina61rc-master-data.*}`)
      - traefik.http.routers.lina61rc-master-data.service=lina61rc-master-data
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
  lina61rc-node1:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always
    container_name: lina61rc-node1
    hostname: lina61rc-node1 
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina61rc-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61rc-node1.loadbalancer.server.port=8181        
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
    depends_on:
      - "lina61rc-master"
  lina61rc-node2:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always    
    container_name: lina61rc-node2
    hostname: lina61rc-node2    
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina61rc-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61rc-node2.loadbalancer.server.port=8181      
    env_file:
     - stack.env              
    networks:
      - easy-docker-host
    depends_on:
      - "lina61rc-master"    
  lina61rc-agent1:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61rc-agent1
    hostname: lina61rc-agent1
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61rc-master
      - LINA_AGENTNAME=lina61rc-agent1
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true        
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61rc-master"
  lina61rc-agent2:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61rc-agent2
    hostname: lina61rc-agent2    
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61rc-master
      - LINA_AGENTNAME=lina61rc-agent2
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61rc-master"
  lina61rc-agent3:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61rc-agent3
    hostname: lina61rc-agent3   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61rc-master
      - LINA_AGENTNAME=lina61rc-agent3
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env        
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61rc-master"
  lina61rc-agent4:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61rc-agent4
    hostname: lina61rc-agent4   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61rc-master
      - LINA_AGENTNAME=lina61rc-agent4
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env           
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61rc-master"      