version: '3'

networks:
  easy-docker-host:
    external: true

services:
  lina60-master:
    image: hub.atempo.cloud/internal/lina:6.0.0-latest-full
    pull_policy: always    
    container_name: lina60-master
    hostname: lina60-master    
    restart: unless-stopped
    ports:
      - 8181
      - 8182      
    environment:
      - LINA_MASTERMODE=1
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    networks:
      - easy-docker-host
  lina60-srv1:
    image: hub.atempo.cloud/internal/lina:6.0.0-latest-full
    pull_policy: always    
    container_name: lina60-srv1
    hostname: lina60-srv1    
    restart: unless-stopped
    ports:
      - 8181
    environment:
      - LINA_MASTER=lina60-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef      
    networks:
      - easy-docker-host
  lina60-srv2:
    image: hub.atempo.cloud/internal/lina:6.0.0-latest-full
    pull_policy: always    
    container_name: lina60-srv2
    hostname: lina60-srv2    
    restart: unless-stopped
    ports:
      - 8181
    environment:
      - LINA_MASTER=lina60-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef        
    networks:
      - easy-docker-host      
  lina60-agent001:
    image: hub.atempo.cloud/internal/lina-agent:6.0.0-latest
    pull_policy: always    
    container_name: lina60-agent001
    hostname: lina60-agent001
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent001 
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"
  lina60-agent002:
    image: hub.atempo.cloud/internal/lina-agent:6.0.0-latest
    pull_policy: always    
    container_name: lina60-agent002
    hostname: lina60-agent002    
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent002   
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"