version: '3'

networks:
  easy-docker-host:
    external: true

services:
  linaflex-master:
    image: registry.atempo.com/public/lina:$VERSION
    pull_policy: always    
    container_name: $COMPOSE_PROJECT_NAME-master
    hostname: $COMPOSE_PROJECT_NAME-master
    restart: unless-stopped
    ports:
      - 8181 # Data port
      - 8182 # Admin port
    environment:
      - ADE_SUPERADMIN_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}
      - ADE_IS_MASTER=1
      - ADE_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
      - ADE_UPDATEURL=https://${COMPOSE_PROJECT_NAME}-master-data.${EXTERNAL_DOMAIN}/Agents
      - ADE_WEBRESTOREURL=https://${COMPOSE_PROJECT_NAME}-master-data.${EXTERNAL_DOMAIN}/AAgent
      - ADE_SERVERNAME=${COMPOSE_PROJECT_NAME}-master-data.${EXTERNAL_DOMAIN}:443
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-master.loadbalancer.server.port=8182
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-master.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-master.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-master.service=$COMPOSE_PROJECT_NAME-master
      - traefik.http.services.$COMPOSE_PROJECT_NAME-master-data.loadbalancer.server.port=8181
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-master-data.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-master-data.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-master-data.service=$COMPOSE_PROJECT_NAME-master-data
    env_file:
     - stack.env    
    networks:
      - easy-docker-host
  linaflex-node1:
    image: registry.atempo.com/public/lina:$VERSION
    pull_policy: always
    container_name: $COMPOSE_PROJECT_NAME-node1
    hostname: $COMPOSE_PROJECT_NAME-node1 
    restart: unless-stopped
    ports:
      - 8181 # Data port
      - 8182 # Admin port
    environment:
      - ADE_SUPERADMIN_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}    
      - ADE_MASTER_NAME=$COMPOSE_PROJECT_NAME-master:8181:8182
      - ADE_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
      - ADE_SERVERNAME=${COMPOSE_PROJECT_NAME}-node1-data.${EXTERNAL_DOMAIN}:443
      - ADE_SERVER_ADMIN_URL=https://${COMPOSE_PROJECT_NAME}-node1.${EXTERNAL_DOMAIN}/
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-node1.loadbalancer.server.port=8182
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node1.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-node1.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node1.service=$COMPOSE_PROJECT_NAME-node1
      - traefik.http.services.$COMPOSE_PROJECT_NAME-node1-data.loadbalancer.server.port=8181
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node1-data.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-node1-data.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node1-data.service=$COMPOSE_PROJECT_NAME-node1-data          
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
    depends_on:
      - "linaflex-master"
  linaflex-node2:
    image: registry.atempo.com/public/lina:$VERSION
    pull_policy: always
    container_name: $COMPOSE_PROJECT_NAME-node2
    hostname: $COMPOSE_PROJECT_NAME-node2 
    restart: unless-stopped
    ports:
      - 8181 # Data port
      - 8182 # Admin port
    environment:
      - ADE_SUPERADMIN_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}
      - ROOT_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}
      - ADE_MASTER_NAME=$COMPOSE_PROJECT_NAME-master:8181:8182
      - ADE_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
      - ADE_SERVERNAME=${COMPOSE_PROJECT_NAME}-node2-data.${EXTERNAL_DOMAIN}:443
      - ADE_SERVER_ADMIN_URL=https://${COMPOSE_PROJECT_NAME}-node2.${EXTERNAL_DOMAIN}/              
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-node2.loadbalancer.server.port=8182
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node2.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-node2.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node2.service=$COMPOSE_PROJECT_NAME-node2
      - traefik.http.services.$COMPOSE_PROJECT_NAME-node2-data.loadbalancer.server.port=8181
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node2-data.rule=HostRegexp(`^$COMPOSE_PROJECT_NAME-node2-data.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-node2-data.service=$COMPOSE_PROJECT_NAME-node2-data          
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
    depends_on:
      - "linaflex-master"  
  linaflex-agent1:
    image: registry.atempo.com/public/lina-agentsimulator:latest
    pull_policy: always    
    container_name: $COMPOSE_PROJECT_NAME-agent1
    hostname: $COMPOSE_PROJECT_NAME-agent1
    restart: unless-stopped
    environment:
      - ROOT_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}
      - LINA_CONNECTION_STRING=$COMPOSE_PROJECT_NAME-agent1@$COMPOSE_PROJECT_NAME-master
      - LINA_EMAIL=user-of-agent1@protectedcorp.com
      - LINA_PROTECTEDPATH=/data
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-agent1.loadbalancer.server.port=27261
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent1.rule=HostRegexp(`^${COMPOSE_PROJECT_NAME}-agent1.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent1.service=$COMPOSE_PROJECT_NAME-agent1 
    depends_on:
      - "linaflex-master"
      - "linaflex-node1"
      - "linaflex-node2"
  linaflex-agent2:
    image: registry.atempo.com/public/lina-agentsimulator:latest
    pull_policy: always    
    container_name: $COMPOSE_PROJECT_NAME-agent2
    hostname: $COMPOSE_PROJECT_NAME-agent2
    restart: unless-stopped
    environment:
      - ROOT_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}
      - LINA_CONNECTION_STRING=$COMPOSE_PROJECT_NAME-agent2@$COMPOSE_PROJECT_NAME-master
      - LINA_EMAIL=user-of-agent2@protectedcorp.com
      - LINA_PROTECTEDPATH=/data
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-agent2.loadbalancer.server.port=27261
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent2.rule=HostRegexp(`^${COMPOSE_PROJECT_NAME}-agent2.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent2.service=$COMPOSE_PROJECT_NAME-agent2 
    depends_on:
      - "linaflex-master"
      - "linaflex-node1"
      - "linaflex-node2"
  linaflex-agent3:
    image: registry.atempo.com/public/lina-agentsimulator:latest
    pull_policy: always    
    container_name: $COMPOSE_PROJECT_NAME-agent3
    hostname: $COMPOSE_PROJECT_NAME-agent3
    restart: unless-stopped
    environment:
      - ROOT_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@} 
      - LINA_CONNECTION_STRING=$COMPOSE_PROJECT_NAME-agent3@$COMPOSE_PROJECT_NAME-master
      - LINA_EMAIL=user-of-agent3@protectedcorp.com
      - LINA_PROTECTEDPATH=/data
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-agent3.loadbalancer.server.port=27261
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent3.rule=HostRegexp(`^${COMPOSE_PROJECT_NAME}-agent3.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent3.service=$COMPOSE_PROJECT_NAME-agent3
    depends_on:
      - "linaflex-master"
      - "linaflex-node1"
      - "linaflex-node2"
  linaflex-agent4:
    image: registry.atempo.com/public/lina-agentsimulator:latest
    pull_policy: always    
    container_name: $COMPOSE_PROJECT_NAME-agent4
    hostname: $COMPOSE_PROJECT_NAME-agent4
    restart: unless-stopped
    environment:
      - ROOT_PASSWORD=${DEFAULT_PASSWORD:-ATempo1992@@}  
      - LINA_CONNECTION_STRING=$COMPOSE_PROJECT_NAME-agent4@$COMPOSE_PROJECT_NAME-master
      - LINA_EMAIL=user-of-agent4@protectedcorp.com
      - LINA_PROTECTEDPATH=/data
    env_file:
     - stack.env
    networks:
      - easy-docker-host
    ports:
      - 27261
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME-agent4.loadbalancer.server.port=27261
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent4.rule=HostRegexp(`^${COMPOSE_PROJECT_NAME}-agent4.{any:.+}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME-agent4.service=$COMPOSE_PROJECT_NAME-agent4
    depends_on:
      - "linaflex-master"
      - "linaflex-node1"
      - "linaflex-node2"