version: '3'

networks:
  easy-docker-host:
    external: true

services:
  lina60-master:
    image: hub.atempo.cloud/releases/lina:6.0.0.22727-full
    pull_policy: always    
    container_name: lina60-master
    hostname: lina60-master
    restart: unless-stopped
    ports:
      - 443 # Used for both webUI only
      - 8181 # Used for data (to nodes and from agents) 
    environment:
      - LINA_MASTERMODE=1
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
  lina60-node1:
    image: hub.atempo.cloud/releases/lina:6.0.0.22727-full
    pull_policy: always
    container_name: lina60-node1
    hostname: lina60-node1 
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina60-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina60-node1.loadbalancer.server.port=8181        
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
    depends_on:
      - "lina60-master"
      
  lina60-node2:
    image: hub.atempo.cloud/releases/lina:6.0.0.22727-full
    pull_policy: always    
    container_name: lina60-node2
    hostname: lina60-node2    
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina60-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina60-node2.loadbalancer.server.port=8181      
    env_file:
     - stack.env              
    networks:
      - easy-docker-host
    depends_on:
      - "lina60-master"    
  lina60-agent1:
    image: hub.atempo.cloud/releases/lina-agent:6.0.0.22727
    pull_policy: always    
    container_name: lina60-agent1
    hostname: lina60-agent1
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent1
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_LINUX_BYPASS_FS_TYPE_TEST=true        
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"
  lina60-agent2:
    image: hub.atempo.cloud/releases/lina-agent:6.0.0.22727
    pull_policy: always    
    container_name: lina60-agent2
    hostname: lina60-agent2    
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent2
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_LINUX_BYPASS_FS_TYPE_TEST=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"
  lina60-agent3:
    image: hub.atempo.cloud/releases/lina-agent:6.0.0.22727
    pull_policy: always    
    container_name: lina60-agent3
    hostname: lina60-agent3   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent3
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_LINUX_BYPASS_FS_TYPE_TEST=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env        
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"
  lina60-agent4:
    image: hub.atempo.cloud/releases/lina-agent:6.0.0.22727
    pull_policy: always    
    container_name: lina60-agent4
    hostname: lina60-agent4   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina60-master
      - LINA_AGENTNAME=lina60-agent4
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_LINUX_BYPASS_FS_TYPE_TEST=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env           
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina60-master"      