version: '3'

networks:
  easy-docker-host:
    external: true

services:
  lina61cr-master:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always    
    container_name: lina61cr-master
    hostname: lina61cr-master
    restart: unless-stopped
    ports:
      - 443 # Used for both webUI only
      - 8181 # Used for data (to nodes and from agents) 
    environment:
      - LINA_MASTERMODE=1
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61cr-master.loadbalancer.server.port=443
      - traefik.http.routers.lina61cr-master.rule=HostRegexp(`{lina61crsubdomains:^lina61cr-master.*}`)
      - traefik.http.routers.lina61cr-master.service=lina61cr-master
      - traefik.http.services.lina61cr-master-data.loadbalancer.server.port=8181
      - traefik.http.routers.lina61cr-master-data.rule=HostRegexp(`{lina61crdatasubdomains:^lina61cr-master-data.*}`)
      - traefik.http.routers.lina61cr-master-data.service=lina61cr-master-data
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
  lina61cr-node1:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always
    container_name: lina61cr-node1
    hostname: lina61cr-node1 
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina61cr-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61cr-node1.loadbalancer.server.port=8181        
    env_file:
     - stack.env      
    networks:
      - easy-docker-host
    depends_on:
      - "lina61cr-master"
  lina61cr-node2:
    image: hub.atempo.cloud/controlreleases/lina:6.1-latest-full
    pull_policy: always    
    container_name: lina61cr-node2
    hostname: lina61cr-node2    
    restart: unless-stopped
    ports:
      - 8181 # Used for both data and webUI
    environment:
      - LINA_MASTER=lina61cr-master
      - LINA_MASTER_ACCESSKEY=1b2bc736-5563-44cf-944c-b17c7beefdef
    labels:
      - traefik.http.services.lina61cr-node2.loadbalancer.server.port=8181      
    env_file:
     - stack.env              
    networks:
      - easy-docker-host
    depends_on:
      - "lina61cr-master"    
  lina61cr-agent1:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61cr-agent1
    hostname: lina61cr-agent1
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61cr-master
      - LINA_AGENTNAME=lina61cr-agent1
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true        
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61cr-master"
  lina61cr-agent2:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61cr-agent2
    hostname: lina61cr-agent2    
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61cr-master
      - LINA_AGENTNAME=lina61cr-agent2
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env         
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61cr-master"
  lina61cr-agent3:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61cr-agent3
    hostname: lina61cr-agent3   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61cr-master
      - LINA_AGENTNAME=lina61cr-agent3
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env        
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61cr-master"
  lina61cr-agent4:
    image: hub.atempo.cloud/controlreleases/lina-agent:6.1-latest
    pull_policy: always    
    container_name: lina61cr-agent4
    hostname: lina61cr-agent4   
    restart: unless-stopped
    environment:
      - LINA_SERVERNAME=lina61cr-master
      - LINA_AGENTNAME=lina61cr-agent4
#      - ROOT_PASSWORD=Atempo1992$$
      - LINA_ADVSETTINGS=HN_AGENT_NOVOLUME_MGMT=true  
#      - LINA_DEBUGMODE=VOLS:5;
    env_file:
     - stack.env           
    networks:
      - easy-docker-host
    ports:
      - 27261
    depends_on:
      - "lina61cr-master"      