version: '3'

networks:
  easy-docker-host:
    external: true

services:
  m4a10-db:
    image: postgres:12
    pull_policy: always
    container_name: m4a10-db
    restart: unless-stopped
    environment:
      - POSTGRES_DATABASE=m4a
      - POSTGRES_USER=m4a
      - POSTGRES_PASSWORD=6PhmavGc#H58q
    networks:
      - easy-docker-host
  m4a10:
    image: hub.atempo.cloud/releases/miria-analytics:1.0-latest
    pull_policy: always    
    container_name: m4a10
    restart: unless-stopped
    networks:
      - easy-docker-host
    privileged: true
    ports:
      - 443
      - 9111
    hostname: m4a10
    environment:
      - POSTGRES_SERVER=m4a10-db
      - POSTGRES_DATABASE=m4a
      - POSTGRES_USER=m4a
      - POSTGRES_PASSWORD=6PhmavGc#H58q 
      - POSTGRES_PORT=5432 
      - INITIAL_PASSWORD=ATempo1992$$    
    labels:
      - traefik.http.services.m4a10.loadbalancer.server.port=443
      - traefik.http.services.m4a10.loadbalancer.server.scheme=https          
    depends_on:
      - "m4a10-db"
  nfs-nas:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs-nas
    restart: unless-stopped
    privileged: true
    networks:
      - easy-docker-host    
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - /docker/nfs-storage:/data
    ports:
      - 2049
