version: '3'

networks:
  easy-docker-host:
    external: true

services:
  mail:
    image: maildev/maildev
    pull_policy: always    
    container_name: mail
    restart: unless-stopped
    ports:
      - 80
      - 25
    labels:
      - traefik.http.services.mail.loadbalancer.server.port=80
    environment:
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    networks:
      - easy-docker-host