version: '3'

networks:
  easy-docker-host:
    external: true

services:
  mail:
    image: maildev/maildev
    pull_policy: always    
    container_name: mail
    restart: unless-stopped
    ports:
      - 80
      - 25:25
    labels:
      - traefik.http.services.mail.loadbalancer.server.port=80
    environment:
      - TZ=Europe/Paris
      - MAILDEV_SMTP_PORT=25
      - MAILDEV_WEB_PORT=80
    networks:
      - easy-docker-host
    healthcheck:
      disable: true
# Env variables are provided by stack, below the list to use them manually if needed :
#    environment:
#      - SYSLOG_USERNAME=root
#      - SYSLOG_PASSWORD=ATempo1992$$   