version: '3'

networks:
  easy-docker-host:
    external: true

services:
  minio-s3:
    image: quay.io/minio/minio:RELEASE.2023-08-23T10-07-06Z
    pull_policy: always    
    container_name: minio-s3
    restart: unless-stopped
    command: server /data --console-address ":9001" --address ":443"
    ports:
      - 443 # To use same data (S3) port from container and externally
      - 9001 # Administration console
    volumes:
     - /data
    labels:

      - traefik.http.services.minio-s3.loadbalancer.server.port=443
      # Will match all URL containing minio-s3.* => forwarding to s3 data port
      - traefik.http.routers.minio-s3.rule=HostRegexp(`(?i)^minio-s3\.(.*)$`)
      - traefik.http.routers.minio-s3.ruleSyntax=v3
      - traefik.http.routers.minio-s3.service=minio-s3
      - traefik.http.services.minio-console.loadbalancer.server.port=9001
      # Will match all URL containing minio-console.* => forwarding to admin console port
      - traefik.http.routers.minio-console.rule=HostRegexp(`(?i)^minio-console\.(.*)$`)
      - traefik.http.routers.minio-console.ruleSyntax=v3
      - traefik.http.routers.minio-console.service=minio-console    

#     - traefik.http.services.minio-s3.loadbalancer.server.port=443
#     # Will match all URL containing minio-s3.* => forwarding to s3 data port
#     - traefik.http.routers.minio-s3.rule=HostRegexp(`minio-s3.{any:.+}`)
#     - traefik.http.routers.minio-s3.service=minio-s3
#     - traefik.http.services.minio-console.loadbalancer.server.port=9001
#     # Will match all URL containing minio-console.* => forwarding to admin console port
#     - traefik.http.routers.minio-console.rule=HostRegexp(`minio-console.{any:.+}`)
#     - traefik.http.routers.minio-console.service=minio-console    
    networks:
      - easy-docker-host
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed :
#    environment:
#      - MINIO_ROOT_USER=root
#      - MINIO_ROOT_PASSWORD=ATempo1992$$        
