version: '3'

networks:
  easy-docker-host:
    external: true

volumes:
  postgres_data:
  s3_data:
  nfs_data:

services:
  miria40-db:
    image: postgres:13.5
    pull_policy: always
    container_name: miria40-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_HOST_AUTH_METHOD=trust # /!\ Unsecured but should fix DB backup from miria  
    networks:
      - easy-docker-host
    env_file:
     - stack.env      
  miria40:
    image: hub.atempo.cloud/releases/miria:4.0-latest
    pull_policy: always
    container_name: miria40
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 80
      - 443
      - 9111
      - 2524
      - 5432
    hostname: miria40
    depends_on:
      - "miria40-db"
      - "miria40-mail"
      - "miria40-syslog"
    environment:
      - POSTGRES_SERVER=miria40-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_PORT=5432
      - MM_AGENT=1
      - MM_SERVER=1
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - POSTGRES_SERVER=miria40-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=rzKX2C5%bVY
#      - POSTGRES_PORT=5432
#      - DB_NAME=MIRIA
#      - INITIAL_PASSWORD=ATempo1992$$
#      - DEMO_LICENSE=1

  miria40-agent1:
    image:  hub.atempo.cloud/releases/miria-agent:4.0-latest
    pull_policy: always
    container_name: miria40-agent1
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: miria40-agent1
    environment:
      - MIRIA_SERVER=miria40
    depends_on:
      - "miria40"
      - "miria40-s3"
      - "miria40-nfs"
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - CUSTOM_CMD=mkdir -p /mnt/nfs-nas && mount -v -o vers=4,loud nfs-nas:/ /nas-mounts/nfs1 

  miria40-agent2:
    image:  hub.atempo.cloud/releases/miria-agent:4.0-latest
    pull_policy: always
    container_name: miria40-agent2
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: miria40-agent2
    environment:
      - MIRIA_SERVER=miria40
    depends_on:
      - "miria40"
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - CUSTOM_CMD=mkdir -p /mnt/nfs-nas && mount -v -o vers=4,loud nfs-nas:/ /nas-mounts/nfs1