version: '3'

networks:
  easy-docker-host:
    external: true

services:
  panmove40beta-db:
    image: postgres:13.5
    pull_policy: always
    container_name: panmove40beta-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
    networks:
      - easy-docker-host
    env_file:
     - stack.env      
  panmove40beta:
    image: hub.atempo.cloud/internal/panmove:4.0.0.3
    pull_policy: always
    container_name: panmove40beta
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 80
      - 443
      - 9111
      - 2524
      - 5432
    hostname: panmove40beta
    depends_on:
      - "panmove40beta-db"
    environment:
      - POSTGRES_SERVER=panmove40beta-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_PORT=5432
      - MM_AGENT=1
      - MM_SERVER=1
    env_file:
     - stack.env
# Env variables are provided by stack, below the list to use them manually if needed : 
#      - POSTGRES_SERVER=panmove40beta-db
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=rzKX2C5%bVY
#      - POSTGRES_PORT=5432
#      - DB_NAME=MIRIA
#      - INITIAL_PASSWORD=ATempo1992$$
#      - DEMO_LICENSE=1      
  panmove40beta-agent1:
    image:  hub.atempo.cloud/internal/panmove-agent:4.0.0.3
    pull_policy: always
    container_name: panmove40beta-agent1
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: panmove40beta-agent1
    environment:
      - MIRIA_SERVER=panmove40beta
    env_file:
     - stack.env      
  panmove40beta-agent2:
    image:  hub.atempo.cloud/internal/panmove-agent:4.0.0.3
    pull_policy: always
    container_name: panmove40beta-agent2
    restart: unless-stopped
    privileged: true # Required to mount NFS
    networks:
      - easy-docker-host
    ports:
      - 2524
    hostname: panmove40beta-agent2
    environment:
      - MIRIA_SERVER=panmove40beta
    env_file:
     - stack.env      