version: '3'

services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always    
    security_opt:
      - no-new-privileges:true
    ports:
      - 5000
    networks: 
      - easy-docker-host
    volumes:
      - registry_data:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true

  registry-browser:
    image:  klausmeyer/docker-registry-browser:latest
    container_name: registry-browser
    restart: always  
    security_opt:
      - no-new-privileges:true
    ports:
      - 8080
    networks: 
      - easy-docker-host
    environment:
      - DOCKER_REGISTRY_URL=http://registry:5000
      - ENABLE_DELETE_IMAGES=true
      - PUBLIC_REGISTRY_URL=https://registry.hostname.com
      - SECRET_KEY_BASE=a096698667cffcc404b171c073b14a9e2722cf0163b16de64ddf71e69816235e41c4b58cbcff5d3c1604e67324d95f271fb7363a5404286dbb5225192905c869
    depends_on:
      - "registry"
volumes:
  registry_data:

networks:
  easy-docker-host:
    external: true
