version: '3'

networks:
  easy-docker-host:
    external: true

services:
  sns:
    image: vardhanv/onprem-sns
    pull_policy: always   
    container_name: sns
    restart: unless-stopped
    ports:
      - 8080
    networks:
      - easy-docker-host