version: '3'

networks:
  easy-docker-host:
    external: true

services:
  ssr:
    image: ${SSR_IMAGE}
    pull_policy: always    
    container_name: ssr
    restart: unless-stopped
    ports:
      - 8080
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.scheme=https
    networks:
      - easy-docker-host
    env_file:
     - stack.env  
