version: '3'

networks:
  easy-docker-host:
    external: true

services:
  tina47:
    image: hub.atempo.cloud/releases/tina:4.7.0.6413
    pull_policy: always   
    container_name: tina47
    restart: unless-stopped
    networks:
      - easy-docker-host
    ports:
      - 80
      - 9111
      - 2525
    hostname: tina47
    env_file:
     - stack.env

# Env variables are provided by stack, below the list to use them manually if needed : 
#      - TINA_ENABLE_HTTP=$TINA_ENABLE_HTTP
#      - TINA_CATALOG_NAME=$TINA_CATALOG_NAME
#      - DEFAULT_USER=$DEFAULT_USER
#      - DEFAULT_PASSWORD=DEFAULT_PASSWORD
#      - PASSWORD_POLICY_MIN_SIZE=11