version: '3'

networks:
  easy-docker-host:
    external: true

services:
  tina2021r1:
    image: hub.atempo.cloud/releases/tina:2021r1
    container_name: tina2021r1
    restart: unless-stopped
    networks:
      - easy-docker-host
    ports:
      - 80
      - 25088:25088
      - 9111
      - 2525
    hostname: tina2021r1
    environment:
      - TINA_ENABLE_HTTP=1
      - TINA_ADMIN_PASSWORD=Atempo1992
      - TINA_CATALOG_MAXSIZE_GB=100
      - TINA_CATALOG_NAME=catalog