version: '3'

networks:
  easy-docker-host:
    external: true

services:
  tinaflex:
    image: hub.atempo.cloud/$VERSION_TYPE/tina:$VERSION
    pull_policy: always   
    container_name: $COMPOSE_PROJECT_NAME
    restart: unless-stopped
    networks:
      - easy-docker-host
    ports:
      - 25088
      - 9111
      - 2525
    hostname: $COMPOSE_PROJECT_NAME
    env_file:
     - stack.env
    labels:
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=25088
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.scheme=https
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=HostRegexp(`{subdomain:^${COMPOSE_PROJECT_NAME}.*}`)
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.service=$COMPOSE_PROJECT_NAME            

# Env variables are provided by stack, below the list to use them manually if needed : 
#      - TINA_ENABLE_HTTP=$TINA_ENABLE_HTTP # won't work in Tina 4.7 ?
#      - TINA_CATALOG_NAME=$TINA_CATALOG_NAME
#      - DEFAULT_USER=$DEFAULT_USER
#      - DEFAULT_PASSWORD=DEFAULT_PASSWORD
#      - PASSWORD_POLICY_MIN_SIZE=11