version: '3'

networks:
  easy-docker-host:
    external: true

services:
  tina48beta:
    image: hub.atempo.cloud/internal/tina:4.8-latest
    pull_policy: always   
    container_name: tina48beta
    restart: unless-stopped
    networks:
      - easy-docker-host
    ports:
      - 25088
      - 9111
      - 2525
    hostname: tina48beta
    env_file:
     - stack.env
    labels:
      - traefik.http.services.tina48beta.loadbalancer.server.port=25088
      - traefik.http.services.tina48beta.loadbalancer.server.scheme=https          

# Env variables are provided by stack, below the list to use them manually if needed : 
#      - TINA_ENABLE_HTTP=$TINA_ENABLE_HTTP # won't work in Tina 4.7 ?
#      - TINA_CATALOG_NAME=$TINA_CATALOG_NAME
#      - DEFAULT_USER=$DEFAULT_USER
#      - DEFAULT_PASSWORD=DEFAULT_PASSWORD
#      - PASSWORD_POLICY_MIN_SIZE=11