version: '3'

networks:
  easy-docker-host:
    external: true

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    pull_policy: always
    restart: always
    networks: 
      - easy-docker-host    
    volumes:
      - /app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro