# Deploys a Miria 3.15 server with 2 agents attached and Media Manager (agent + server) enabled on Miria Server
# will listen on port 8443 (HTTPS) and 8080 (HTTP)
# webui is on /webapp/ (link is available on first page)
# default login : root / (empty password)
# Next step : manually enable demo license (15 days) and add waiting agents in infrastructure
# connect NFS share inside data movers containers using command : mkdir /myshare && mount -v -t nfs -o nolock nas-server:/nfs-export /myshare

version: '3'

services:
  miria315-db:
    image: postgres:13.5
    pull_policy: always
    container_name: miria315-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY  
  miria315:
    image: hub.atempo.cloud/releases/miria:3.15.0.7
    pull_policy: always
    container_name: miria315
    restart: unless-stopped
    ports:
      - 8080:80
      - 8443:443
      - 2524
    hostname: miria315
    depends_on:
      - "miria315-db"
    environment:
      - POSTGRES_SERVER=miria315-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=rzKX2C5%bVY
      - POSTGRES_PORT=5432
      - MM_AGENT=1
      - MM_SERVER=1    
  miria315-agent1:
    image:  hub.atempo.cloud/releases/miria-agent:3.15.0.7
    pull_policy: always
    container_name: miria315-agent1
    restart: unless-stopped
    privileged: true # Needed to mount NFS share inside container    
    ports:
      - 2524
    hostname: miria315-agent1
    environment:
      - MIRIA_SERVER=miria315   
  miria315-agent2:
    image:  hub.atempo.cloud/releases/miria-agent:3.15.0.7
    pull_policy: always
    container_name: miria315-agent2
    restart: unless-stopped
    privileged: true # Needed to mount NFS share inside container    
    ports:
      - 2524
    hostname: miria315-agent2
    environment:
      - MIRIA_SERVER=miria315   